name: Build Windows EXE
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          # Correction du nom du paquet : embree tout court au lieu de embree3
          vcpkg install embree armadillo octomap hdf5 tbb --triplet x64-windows
          
      - name: Compile Manual
        run: |
          g++ compute_visibility.cc `
          -o compute_visibility.exe `
          -std=c++14 `
          -D_GLIBCXX_USE_CXX11_ABI=1 `
          -DARMA_USE_HDF5 `
          -I"C:/vcpkg/installed/x64-windows/include" `
          -L"C:/vcpkg/installed/x64-windows/lib" `
          -larmadillo -lembree -loctomap -loctomath -lhdf5 -ltbb -lws2_32
          
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: mon-exécutable-windows
          path: ./*.exe
